# Generated by Django 5.1.7 on 2026-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_comment_options_comment_guest_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="vi_cast",
            field=models.TextField(
                blank=True, default="", help_text="Comma-separated cast names"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_country",
            field=models.CharField(
                blank=True, default="", help_text="e.g. South Korea", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_episodes",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 12 or Ongoing", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_filesize",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 102 MB", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_genre",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Drama, Romance", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_language",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Korean", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_runtime",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 00:46:43", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. Completed / On Going",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_subtitle",
            field=models.CharField(
                blank=True, default="", help_text="e.g. English", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="vi_year",
            field=models.CharField(
                blank=True, default="", help_text="e.g. 2026", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="is_blockbuster",
            field=models.BooleanField(
                default=False,
                help_text="Legacy flag — blockbusters are now auto-computed by views (>=1000)",
            ),
        ),
    ]
