# Generated by Django 5.1.7 on 2026-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movie_vi_cast_movie_vi_country_movie_vi_episodes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="download_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Download URL"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Cover Image URL"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video_url",
            field=models.URLField(max_length=500, verbose_name="Video/Embed URL"),
        ),
    ]
