# Generated by Django 5.1.7 on 2026-05-28 21:05

from django.db import migrations, models
from django.utils.text import slugify


def add_slug_column(apps, schema_editor):
    schema_editor.execute(
        "ALTER TABLE movies_category ADD COLUMN IF NOT EXISTS slug varchar(120) NOT NULL DEFAULT '';"
    )


def backfill_category_slugs(apps, schema_editor):
    """Backfill using raw SQL so we don't depend on ORM field state."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, name FROM movies_category ORDER BY id;")
        rows = cursor.fetchall()

    existing_slugs = set()
    updates = []

    for cat_id, name in rows:
        base = slugify(name) or f"category-{cat_id}"
        slug = base
        n = 1
        while slug in existing_slugs:
            n += 1
            slug = f"{base}-{n}"
        existing_slugs.add(slug)
        updates.append((slug, cat_id))

    with schema_editor.connection.cursor() as cursor:
        for slug, cat_id in updates:
            cursor.execute(
                "UPDATE movies_category SET slug = %s WHERE id = %s;",
                [slug, cat_id]
            )


def add_unique_index(apps, schema_editor):
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS movies_category_slug_key ON movies_category (slug);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS movies_category_slug_ca1e303d_like "
        "ON movies_category (slug varchar_pattern_ops);"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_movie_slug"),
    ]

    operations = [
        # Step 1: Add column via raw SQL
        migrations.RunPython(add_slug_column, migrations.RunPython.noop),

        # Step 2: Backfill via raw SQL (ORM can't see the column yet)
        migrations.RunPython(backfill_category_slugs, migrations.RunPython.noop),

        # Step 3: Add indexes now that every row has a unique slug
        migrations.RunPython(add_unique_index, migrations.RunPython.noop),

        # Step 4: Sync Django's state machine (no DB ops, already done above)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="category",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        help_text="Auto-generated from name. Used in SEO URLs.",
                        max_length=120,
                        unique=True,
                    ),
                ),
            ],
            database_operations=[],
        ),

        # Step 5: Alter movie slug
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from title. Used in SEO URLs.",
                max_length=250,
                unique=True,
            ),
        ),
    ]