# Generated by Django 5.1.7 on 2026-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_category_slug_alter_movie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="stream_url",
            field=models.URLField(
                blank=True,
                help_text="Embeddable streaming player URL (e.g. moviebox / streamimdb). Separate from download — powers the stream gate. A movie can have downloads AND streaming at the same time.",
                max_length=600,
                null=True,
                verbose_name="Stream/Embed URL",
            ),
        ),
    ]
