# Generated by Django 5.1.7 on 2026-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_movie_stream_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="season_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Season number parsed from the title, if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="show_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Normalized, season-stripped key grouping all seasons of a show (e.g. 'from'). Auto-derived from the title on save.",
                max_length=250,
            ),
        ),
    ]
