# Generated by Django 5.1.7 on 2026-06-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_app_shows_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.FloatField(
                blank=True, help_text="TMDB rating (0–10).", null=True
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Matched TheMovieDB id, if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_synced",
            field=models.BooleanField(
                default=False, help_text="TMDB enrichment has been attempted."
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(
                blank=True,
                help_text="Official YouTube trailer (from TMDB).",
                max_length=500,
                null=True,
                verbose_name="Trailer URL",
            ),
        ),
    ]
