# Generated by Django 5.1.7 on 2026-06-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0012_cast_grants"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(db_index=True, unique=True)),
                ("media_type", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("release_date", models.CharField(blank=True, max_length=20)),
                ("poster_url", models.URLField(blank=True, max_length=500, null=True)),
                ("trailer_url", models.URLField(blank=True, max_length=500, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["release_date"],
            },
        ),
    ]
