# Generated by Django 5.1.7 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_upcoming_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="on_netflix",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Also streaming on Netflix (region NG).",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="on_prime",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Also streaming on Amazon Prime Video (region NG).",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="providers_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When watch-provider availability was last refreshed.",
                null=True,
            ),
        ),
    ]
