# Generated by Django 5.1.7 on 2026-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0015_movie_on_netflix_movie_on_prime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_seasons",
            field=models.TextField(
                blank=True,
                default="",
                help_text='JSON map of season_number → episode_count for series, from TMDB (e.g. {"1": 10, "2": 8}). Powers the episode selector.',
            ),
        ),
    ]
