# Generated by Django 5.1.7 on 2026-06-28 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0016_movie_tmdb_seasons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title_b_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="views",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
