# Generated by Django 5.1.7 on 2026-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0017_alter_movie_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downloadlink",
            options={"ordering": ["season_number", "episode_number", "priority"]},
        ),
        migrations.AddField(
            model_name="downloadlink",
            name="episode_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadlink",
            name="priority",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="downloadlink",
            name="season_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadlink",
            name="source",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlink",
            index=models.Index(
                fields=["movie", "season_number", "episode_number"],
                name="movies_down_movie_i_7fdfb3_idx",
            ),
        ),
    ]
