# Generated by Django 5.1.7 on 2026-07-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0018_alter_downloadlink_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True, default="")),
                ("hot_take", models.TextField(blank=True, default="")),
                ("url", models.URLField(max_length=600, unique=True)),
                ("source", models.CharField(blank=True, default="", max_length=80)),
                ("image_url", models.URLField(blank=True, default="", max_length=600)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("user_name", models.CharField(blank=True, default="", max_length=80)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="movies.newspost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("emoji", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="movies.newspost",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(
                fields=["is_published", "-published_at"],
                name="movies_news_is_publ_6aa63c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newspost",
            index=models.Index(
                fields=["category", "-published_at"],
                name="movies_news_categor_6b1f40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsreaction",
            index=models.Index(
                fields=["news", "emoji"], name="movies_news_news_id_2a55d1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newsreaction",
            unique_together={("news", "user_id")},
        ),
    ]
