# Generated by Django 5.1.7 on 2026-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0019_newspost_newscomment_newsreaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=140)),
                ("message", models.TextField()),
                ("user_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("handled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
