# Generated by Django 5.1.7 on 2026-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0021_newscomment_created_at_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres_synced",
            field=models.BooleanField(
                default=False, help_text="TMDB genres have been linked as categories."
            ),
        ),
    ]
