# Generated by Django 5.1.7 on 2026-08-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0022_movie_genres_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadlink",
            name="telegram_message_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
