# Generated by Django 5.1.7 on 2026-09-24 22:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0023_downloadlink_telegram_message_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="IMDb id (e.g. 'tt1234567'), from TMDB external_ids. Used to fetch IMDb/Rotten Tomatoes ratings via OMDb.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExternalRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("imdb", "IMDb"),
                            ("rt", "Rotten Tomatoes"),
                            ("letterboxd", "Letterboxd"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Normalized 0–10 score, for averaging across sources."
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Native display string, e.g. '87%', '7.8/10'.",
                        max_length=20,
                    ),
                ),
                ("audience_score", models.FloatField(blank=True, null=True)),
                (
                    "audience_display",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_ratings",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "source")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="1–10 scale, displayed as 0.5–5.0 stars (rating / 2).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="Optional written review."
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="movies.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("movie", "user")},
            },
        ),
    ]
