# Generated by Django 5.1.7 on 2026-09-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0024_movie_imdb_id_externalrating_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        help_text="e.g. Director, Writer, Producer", max_length=100
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("directing", "Directing"),
                            ("writing", "Writing"),
                            ("production", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_credits",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_roles",
                        to="movies.person",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("movie", "person", "job")},
            },
        ),
    ]
