# Generated by Django 5.1.7 on 2026-09-26 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0025_moviecrew"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="verified_watched_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="verified_watched_movies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="watched_by",
            field=models.ManyToManyField(
                blank=True, related_name="watched_movies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="NotifyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("media_type", models.CharField(default="movie", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tmdb_id")},
            },
        ),
    ]
