# Generated by Django 5.1.7 on 2026-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0028_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="weekly_views",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
