# Generated by Django 5.1.7 on 2026-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0030_profile_custom_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="custom_avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Fixed avatar (e.g. the site logo for the official Watch2D account) — takes priority over the generated one.",
                max_length=500,
            ),
        ),
    ]
