# Generated by Django 5.1.7 on 2026-09-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0031_alter_profile_custom_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="backdrop_url",
            field=models.URLField(
                blank=True,
                help_text="Wide landscape still from TMDB, used as the movie detail page's hero banner (separate from the poster).",
                max_length=500,
                null=True,
                verbose_name="Backdrop Image URL",
            ),
        ),
    ]
